In [1]:
#for installing the numpy
!pip install numpy


#import numpy module with alias np
import numpy as np

In [2]:
#define a numpy array passing a list with 1,2 and 3 as elements in it
a = np.array([1,2,3,4,"a"])
#print a
a

array(['1', '2', '3', '4', 'a'], dtype='<U11')

In [5]:
#define a,b,c and d as instructed below       
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
#print dimensions of a,b,c and d          using .ndim()
print('a dimension:',a.ndim)
print('b dimension:',b.ndim)
print('c dimension:',c.ndim)
print('d dimension:',d.ndim)


a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [6]:
#print shape of each a,b,c and d       using.shape()
print(a)
print("shape of a:",a.shape)
print(b)
print("shape of b:",b.shape)
print(c)
print("shape of c:",c.shape)
print(d)
print("shape of d:",d.shape)

10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
shape of d: (1, 4, 3)


In [7]:
#print datatype of a,b,c and d   using dtype()
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int32
int32
int32
int32


In [8]:
#print type of variable  using type()
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
#print length of array b, using len()
len(d)

1

In [17]:
#create a numpy array using arange with 1 and 9 as parameter in it using arange()
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
#create a numpy array using arange with 1,9 and 3 as parameters using arange()     start,stop,skip
np.arange(1,9,3)

array([1, 4, 7])

In [21]:
#create numpy array using eye function with 5 as passed parameter  using eye()
np.eye(4 ,dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#create numpy array using eye function with 3 as passed parameter using eye()
np.eye(2 ,dtype=int)       #hence identity matrices

array([[1, 0],
       [0, 1]])

In [33]:
#create numpy using zero function with(3,2) as passed parameter  using zeros()
np.zeros((6,6),dtype='int')      #hence null matrices

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [34]:
#numpy using ones function with (4,5) as passed parameter   using ones()
np.ones((4,5))                 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
#numpy using full function with (2,3 ) and 2 as passed paramter  using full()
np.full((3,2),721,dtype=int)

array([[721, 721],
       [721, 721],
       [721, 721]])

In [36]:
#using diag function passing a list [1,2,3,4,5,6]      using diad()
x =[1,2,3,4,5,6]
np.diag(x)         

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [49]:
#using arange() to generate numpy array x with numbers between 1 to 16
x=np.arange(1,17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [50]:
#using reshape x with 2 rows 8 columns          using reshape()
n=x.reshape((8,2))
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [53]:
n1=n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [54]:
#converting to old dimension   using ravel()=restore previous
v=n.ravel()
print(v)
print(v.shape)
print(v.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [55]:
#using flattening x convert into one dimensional  using flatten()
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [57]:
#even numbers between 1 to 25
a=np.arange(4,7,19)
print(a)

[4]


In [64]:
#get third element in array a
a[0]

4

In [65]:
#print 2nd,6th,8th element in array a
a[0:4:2]

array([4])

In [66]:
#define an array 2-D with [[1,2,3],[4,5,6],[7,8,9]] as its elements
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
#print 3rd element of 3rd row of a
a[2,2]

9

In [73]:
#define an array b again with ([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]) as its elements
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b.shape
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
#print 3rd element from 2nd list in nested list passed
b[0][0][2]

3

In [74]:
#slicing
arr=np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
#slice elements from 1 to 5 from arrar arr:
arr[0:5]

array([1, 2, 3, 4, 5])

In [76]:
#slice elements from index 6 to the end of the array arr:
arr[6:]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
#slice elements from the beginning to index 5(not included) in array arr:
arr[0:5]

array([1, 2, 3, 4, 5])

In [79]:
#print every other element from index 1 to index 7
arr[1:7:2]

array([2, 4, 6])

In [80]:
#return every other element from the entire array arr:
arr[0:10:2]

array([1, 3, 5, 7, 9])

In [81]:
#print array a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
#in array a print index 2 from all the rows
arr[2]

3

In [88]:
x1= np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
#assign x2=x1
x2=x1 #view

In [90]:
#print x1 and x2
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [91]:
#change 1st element of x2 as 10
x2[0]=10

In [92]:
#again print x1 and x2
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [118]:
print(id(x1))
print(id(x2))

2696102701936
2696102701936


In [114]:
#check memory share between x1 and x2
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

True
2696102701936
2696102701936


In [116]:
#create a view of x1 and store it in x3
x3 = x1.view()

In [117]:
#again check memory share between x1 and x3
np.shares_memory(x1, x3)

True

In [119]:
#change 1st element of x3=10
x3[0]=10
#print x1 and x3 to check if changes reflected in both 
print(x1)
print(x3)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [121]:
#now create an array x4 which is copy of x1 using copy()
x4=np.copy(x1)
#change the last element of x4 as 100
x4[-1]=100
#print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 100]


In [122]:
#check memory share between x1 and x4
print(id(x1))
print(id(x4))
np.shares_memory(x1,x4)

2696102701936
2696102754128


False

In [123]:
#print a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
#check if every element in array a greater than 3 or not using'>'notation
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [125]:
#get a list with all elements of array 'a' greater than 3
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [126]:
#get a list with all elements of array 'a' greater than 3 but less than 6
a[(a>3)&(a<6)]

array([4, 5])

In [127]:
#check if each elements in array 'x1' equals 'x4' using ''=='' notation
x1==x4
#print(x1)
#print(x4)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [131]:
#transpose
#print transpose of array 'a'    using transpose()   rows becomes columns
print (a.transpose())
#print array 'a'
print("--------------")
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
--------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [129]:
#stack x1 and x4 along columns    using vstack()=vertical
print(x1)
print(x4)
np.vstack((x1,x4))

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 100]


array([[ 10,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,   1,   2,   3,   4,   5,   6,   7,   8, 100]])

In [130]:
#stack x1 and x4 along rows     using hstack=horizontal
np.hstack((x1,x4))

array([ 10,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,   1,   2,
         3,   4,   5,   6,   7,   8, 100])

In [132]:
#inserts values into arrays x1 before index 4 with elements of x4  using insert()
print(x1)
print(x4)
np.insert(x1,4,x4)

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 100]


array([ 10,   1,   2,   3,  10,   1,   2,   3,   4,   5,   6,   7,   8,
       100,   4,   5,   6,   7,   8,   9])

In [133]:
#delete 2nd element from array x2  using delete()
print(x2)
np.delete(x2,0)

[10  1  2  3  4  5  6  7  8  9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
#mathematical operations on numpy array
#defining a
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
#print trignometric sin value of each element of a 
np.sin(a)
(np.sin(a))/(np.cos(a))

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [135]:
#print trignometric cos value of each element of a
print(np.cos(a))
print(np.tan(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [136]:
#print exponential value of each elements of a using exp()
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [137]:
#print total sum of elements of a
np.sum(a)

45

In [138]:
#print sum in array a column wise
np.sum(a,axis=1)

array([ 6, 15, 24])

In [140]:
#print sum in array a row wise
np.sum(a,axis=0)

array([12, 15, 18])

In [ ]:
#mean(average)=sum of total values/no of values
#median(middle)=arrange in ascending to decending order than pick the middle value
#mode(most repeated value)=number which repeats most
#range(difference)=difference between largest and smallest number
#standard deviation s=square root of sigma(x-xbar)2/(n-1)


In [141]:
#print median of array a  using median()
np.median(a)

5.0

In [142]:
#print mean of array a  using mean()
np.mean(a)

5.0

In [143]:
#print standard deviation of array a  using std()
np.std(a)

2.581988897471611

In [144]:
#print largest element present in array a using max()
np.max(a)

9

In [145]:
#print sorted x4 array  using sort()
np.sort(x4)

array([  1,   2,   3,   4,   5,   6,   7,   8,  10, 100])

In [146]:
#where()method is used to finding the index
import numpy as np
#create a numpy array
arr=np.array([[12,14,16,18,28,45]])
#use numpy where()with 1 dimentional arrays
arr1=np.where(arr>16)
print(arr1)

(array([0, 0, 0], dtype=int64), array([3, 4, 5], dtype=int64))


In [147]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [148]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [149]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [150]:
print(len(keyword.kwlist))

36
